"use client"

import { useState } from 'react'
import Navbar from '@/components/Navbar'
import LanguageToggle from '@/components/LanguageToggle'
import { useLanguage } from '@/components/LanguageProvider'
import { agentsData } from './agentsData'

const categories = [
  { id: 'all', no: 'Alle', en: 'All' },
  { id: 'academic', no: 'Akademisk', en: 'Academic' },
  { id: 'design', no: 'Design', en: 'Design' },
  { id: 'engineering', no: 'Ingeniør', en: 'Engineering' },
  { id: 'game-development', no: 'Spillutvikling', en: 'Game Development' },
  { id: 'integrations', no: 'Integrasjoner', en: 'Integrations' },
  { id: 'marketing', no: 'Markedsføring', en: 'Marketing' },
  { id: 'paid-media', no: 'Betalt Media', en: 'Paid Media' },
  { id: 'product', no: 'Produkt', en: 'Product' },
  { id: 'project-management', no: 'Prosjektledelse', en: 'Project Management' },
  { id: 'sales', no: 'Salg', en: 'Sales' },
  { id: 'spatial-computing', no: 'Spatial', en: 'Spatial Computing' },
  { id: 'specialized', no: 'Spesialisert', en: 'Specialized' },
  { id: 'strategy', no: 'Strategi', en: 'Strategy' },
  { id: 'support', no: 'Støtte', en: 'Support' },
  { id: 'testing', no: 'Testing', en: 'Testing' },
]

export default function AgenterPage() {
  const { lang, t } = useLanguage()
  const [valgtAgent, setValgtAgent] = useState<typeof agentsData[0] | null>(null)
  const [aktivKategori, setAktivKategori] = useState('all')
  
  const filtrerteAgenter = aktivKategori === 'all' 
    ? agentsData 
    : agentsData.filter(a => a.category === aktivKategori)

  const lastNedAgent = (agent: typeof agentsData[0]) => {
    const name = lang === 'no' ? (agent.name_no || agent.name) : agent.name
    const description = lang === 'no' ? (agent.description_no || agent.description) : agent.description
    
    const content = `# ${agent.emoji} ${name}

${description}

---
*Generated by Berentsen Labs*
`
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${agent.id}.md`
    a.click()
  }

  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-950">
      <Navbar />
      <LanguageToggle />

      {/* Hero - Brutalist */}
      <section className="pt-32 pb-20 px-6 border-b border-zinc-200">
        <div className="max-w-4xl mx-auto">
          <div className="text-xs text-zinc-400 mb-8 tracking-widest uppercase">
            {t('heroAgentsBadge')}
          </div>
          <h1 className="text-5xl md:text-6xl lg:text-7xl font-light leading-none tracking-tight mb-8">
            {t('heroAgentsTitle1')}<br />
            <span className="text-zinc-400">{t('heroAgentsTitle2')}</span>
          </h1>
          <p className="text-lg text-zinc-500 max-w-xl">
            {t('heroAgentsDesc')}
          </p>
        </div>
      </section>

      {/* Kategorier */}
      <section className="py-6 px-6 border-b border-zinc-200 bg-zinc-100">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-wrap gap-2">
            {categories.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setAktivKategori(cat.id)}
                className={`px-4 py-2 text-sm font-medium transition-colors ${
                  aktivKategori === cat.id 
                    ? 'bg-zinc-950 text-zinc-50' 
                    : 'bg-zinc-50 text-zinc-600 hover:bg-zinc-200'
                }`}
              >
                {lang === 'no' ? cat.no : cat.en}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Agenter Grid - Brutalist */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-xs text-zinc-400 mb-12 tracking-widest uppercase">
            {lang === 'no' ? 'Alle' : 'All'} — {filtrerteAgenter.length}
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-px bg-zinc-200">
            {filtrerteAgenter.map((agent) => (
              <div 
                key={agent.id}
                className="bg-zinc-50 p-6 hover:bg-zinc-100 transition-colors cursor-pointer"
                onClick={() => setValgtAgent(agent)}
              >
                <div className="text-3xl mb-4">{agent.emoji}</div>
                <h3 className="text-base font-medium mb-1">
                  {lang === 'no' ? (agent.name_no || agent.name) : agent.name}
                </h3>
                <p className="text-sm text-zinc-500 mb-4 line-clamp-2">
                  {lang === 'no' ? (agent.description_no || agent.description) : agent.description}
                </p>
                <div className="text-xs text-zinc-400 uppercase tracking-wider">
                  {categories.find(c => c.id === agent.category)?.[lang === 'no' ? 'no' : 'en'] || agent.category}
                </div>
                <button 
                  className="w-full mt-4 px-4 py-2 border border-zinc-950 text-sm font-medium hover:bg-zinc-950 hover:text-zinc-50 transition-colors"
                  onClick={(e) => { e.stopPropagation(); lastNedAgent(agent); }}
                >
                  ↓ {t('download')}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Detail Modal - Brutalist */}
      {valgtAgent && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/80 backdrop-blur-sm" onClick={() => setValgtAgent(null)}>
          <div className="bg-zinc-50 border border-zinc-200 max-w-2xl w-full max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="sticky top-0 bg-zinc-50 border-b border-zinc-200 p-6 flex items-start justify-between">
              <div>
                <div className="text-4xl mb-2">{valgtAgent.emoji}</div>
                <h2 className="text-2xl font-medium">
                  {lang === 'no' ? (valgtAgent.name_no || valgtAgent.name) : valgtAgent.name}
                </h2>
              </div>
              <button onClick={() => setValgtAgent(null)} className="text-2xl text-zinc-400 hover:text-zinc-950 transition-colors">×</button>
            </div>
            <div className="p-6 space-y-6">
              <div>
                <h3 className="text-xs text-zinc-400 uppercase tracking-widest mb-2">{t('description')}</h3>
                <p className="text-zinc-600">
                  {lang === 'no' ? (valgtAgent.description_no || valgtAgent.description) : valgtAgent.description}
                </p>
              </div>
              <div>
                <h3 className="text-xs text-zinc-400 uppercase tracking-widest mb-2">{t('category')}</h3>
                <span className="px-3 py-1.5 bg-zinc-950 text-zinc-50 text-sm">
                  {categories.find(c => c.id === valgtAgent.category)?.[lang === 'no' ? 'no' : 'en'] || valgtAgent.category}
                </span>
              </div>
            </div>
            <div className="sticky bottom-0 bg-zinc-50 border-t border-zinc-200 p-6 flex gap-4">
              <button className="flex-1 px-6 py-3 bg-zinc-950 text-zinc-50 font-medium hover:bg-zinc-800 transition-colors" onClick={() => { lastNedAgent(valgtAgent); setValgtAgent(null); }}>
                ↓ {t('downloadMd')}
              </button>
              <button className="px-6 py-3 border border-zinc-300 font-medium hover:border-zinc-950 transition-colors" onClick={() => setValgtAgent(null)}>
                {t('close')}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* CTA - Brutalist */}
      <section className="py-24 px-6 bg-zinc-100 border-t border-zinc-200">
        <div className="max-w-3xl mx-auto text-center">
          <div className="text-3xl md:text-4xl font-light leading-tight mb-6">
            {t('needHelp')} <span className="text-zinc-400">{t('help')}</span>?
          </div>
          <p className="text-zinc-500 mb-8 max-w-md mx-auto">
            {t('helpDesc')}
          </p>
          <a href="mailto:vegarberentsen@gmail.com" className="inline-flex items-center gap-2 px-6 py-3 bg-zinc-950 text-zinc-50 font-medium hover:bg-zinc-800 transition-colors">
            {t('contact')} →
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-zinc-200">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="text-xl font-medium tracking-tight">
            <span className="text-zinc-950">Berentsen</span>
            <span className="text-zinc-400">Labs</span>
          </div>
          <div className="text-sm text-zinc-400">
            © {new Date().getFullYear()} Berentsen Labs. {t('rights')}
          </div>
        </div>
      </footer>
    </div>
  )
}
